version: '3.3'

services:
  app:
    image: node:18.20.2
    restart: always
    working_dir: /usr/src/app
    ports:
      - "80:3002"
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    command: bash -c 'npm cache clean --force && npm install && npm start'
    environment:
      - CONNECTION_STRING=mysql://root:banco123@db:3306/banco_musical_bridge
    depends_on:
      - db

  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: banco123
      MYSQL_DATABASE: banco_musical_bridge
    ports:
      - "3306:3306"  # Utilize a porta padrão 3306 para dentro e fora do container
    volumes:
      - ./db:/var/lib/mysql
