version: '3.8'

services:
  app:
    image: node:16.14.0
    restart: always
    working_dir: /usr/src/app
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: "bash -c 'npm install && npm audit fix && npm start'"

  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: banco123
      MYSQL_DATABASE: banco_musical_bridge
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql
