version: '3.3'
services:
  app:
    build: .
    ports:
      - "3002:3002"
    depends_on:
      - db
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: banco123
      MYSQL_DATABASE: banco_musical_bridge
      MYSQL_USER: root
      MYSQL_PASSWORD: banco123
    ports:
      - "3306:3306"
